# Generated by Django 5.2.7 on 2025-10-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("vocabulary", models.JSONField(blank=True, default=list)),
                ("grammar", models.JSONField(blank=True, default=list)),
                ("exercises", models.JSONField(default=list)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lessons",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="userprogress",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="userprogress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
