# Generated by Django 5.2.7 on 2025-11-10 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mascot_achievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100)),
                ('exercise_id', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Opción Múltiple'), ('TRANSLATION', 'Traducción'), ('FILL_IN_THE_BLANK', 'Completar Espacios')], max_length=20)),
                ('is_correct', models.BooleanField()),
                ('user_answer', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'exercise_type'], name='exercise_re_user_id_7d4bce_idx'), models.Index(fields=['user', 'lesson_id'], name='exercise_re_user_id_5ac520_idx')],
            },
        ),
    ]
