# Generated by Django 5.2.7 on 2025-11-11 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exerciseresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_word', models.CharField(max_length=200)),
                ('guarani_word', models.CharField(max_length=200)),
                ('example', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('deck_name', models.CharField(blank=True, default='General', max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('times_reviewed', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flashcards',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'spanish_word', 'guarani_word')},
            },
        ),
    ]
