# Generated by Django 5.2.7 on 2025-11-11 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dailychallenge_studysession_userstreak_activitylog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Conversación Libre'), ('MARKET', 'En el Mercado'), ('GREETINGS', 'Saludos y Presentaciones'), ('RESTAURANT', 'En el Restaurante'), ('EMERGENCY', 'Emergencias'), ('HOME', 'En Casa'), ('CELEBRATION', 'Celebraciones')], max_length=50, unique=True)),
                ('icon', models.CharField(default='💬', max_length=10)),
                ('description', models.TextField()),
                ('system_prompt', models.TextField()),
                ('example_phrases', models.JSONField(default=list)),
                ('difficulty_level', models.CharField(default='beginner', max_length=20)),
            ],
            options={
                'db_table': 'conversation_modes',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('message_count', models.IntegerField(default=0)),
                ('difficulty_level', models.CharField(default='beginner', max_length=20)),
                ('words_used', models.IntegerField(default=0)),
                ('new_words_learned', models.JSONField(default=list)),
                ('grammar_errors', models.IntegerField(default=0)),
                ('pronunciation_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.conversationmode')),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('is_user_message', models.BooleanField(default=True)),
                ('detected_language', models.CharField(default='es', max_length=10)),
                ('grammar_corrections', models.JSONField(blank=True, default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('sentiment', models.CharField(default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('TURNS', 'Mantener X turnos de conversación'), ('VERBS', 'Usar X verbos diferentes'), ('TOPIC', 'Hablar sobre un tema específico'), ('TRANSLATE', 'Traducir X frases correctamente'), ('QUESTIONS', 'Hacer X preguntas')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('target_value', models.IntegerField()),
                ('xp_reward', models.IntegerField(default=30)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.conversationmode')),
            ],
            options={
                'db_table': 'conversation_challenges',
            },
        ),
        migrations.CreateModel(
            name='GrammarCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('corrected_text', models.TextField()),
                ('error_type', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Leve'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='api.chatmessage')),
            ],
            options={
                'db_table': 'grammar_corrections',
            },
        ),
        migrations.CreateModel(
            name='UserConversationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(choices=[('A1', 'Principiante'), ('A2', 'Elemental'), ('B1', 'Intermedio'), ('B2', 'Intermedio Alto'), ('C1', 'Avanzado'), ('C2', 'Maestría')], default='A1', max_length=2)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('vocabulary_size', models.IntegerField(default=0)),
                ('grammar_score', models.FloatField(default=0.0)),
                ('vocabulary_score', models.FloatField(default=0.0)),
                ('fluency_score', models.FloatField(default=0.0)),
                ('comprehension_score', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_level', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_conversation_levels',
            },
        ),
    ]
